---
title: "Learning Reflection"
subtitle: "Week 6"
format:
  html:
    embed-resources: true
editor: visual
---

# Learning reflections

Learning reflections are part of your weekly homework and have a weight of 20% of your final grade. Write a reflection in your own words on the different parts of the weeks material below. You can also use your learning reflections as a notebook as you work through exercises or readings. Write as much as you like, but a minimum of 100 words in total.

# Lecture

This lecture was a nice closing piece to show us how to publish or present our findings. I will be leading a workshop later this week on my data, so I was hoping we would go over how to properly render it before then.

# Homework Assignment

Each of the homeworks this week were a good overview of our past lectures and homeworks. I am thankful we had these as a homework with provided solutions to check our answers, rather than an exam. I think using our new knowledge on a capstone project is a much better way to represent our understandings as well.

# Readings

R for Data Science - Section 13 - Relational data:

“The variables used to connect each pair of tables are called keys. A key is a variable (or set of variables) that uniquely identifies an observation.” – can be primary or foreign. Inner joins vs outer joins, lecture says almost always use left_join. This chapter was a bit hard to understand with just the reading but the figures along with it were very helpful.

# Submit learning reflections

## Stage, Commit & Push to GitHub

This final section introduces the workflow you need to follow at the end of each live coding exercise, homework assignment, learning reflection. It ensures that all the changes you have made to files in this repository (folder) are synced with the version that is stored on GitHub. The steps will be described at the end of each of the files.

1.  Open the Git pane in RStudio. It's in the top right corner in a separate tab.
2.  **Stage** your changes by checking appropriate box next to all files (if you select one file with your mouse, you can then highlight them all with Ctrl + A on your keyboard and check all boxes)
3.  Write a meaningful commit message (e.g. "Completed week 6 learning reflection") in the **Commit message** box
4.  Click **Commit**. Note that every commit needs to have a commit message associated with it.
5.  Click **Push** to send your changes to GitHub.
6.  Go to your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username) and refresh the page. You should see your commit message next to the updated files.

## Open an issue on GitHub

Once you have ensured that the Quarto document renders without errors and you have pushed all your changes to GitHub, it is to complete the assignment by opening an issue on your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username).

1.  Navigate to your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username).
2.  Click on **Issues**, and then **New issue** button.
3.  Write a meaningful title in the **Title** field
4.  Tag the course instructor with using the `@` sign in combination with `larnsce` as the username
5.  Add any questions or comments
